=== cabrasky/thermal-ticket-printer/templates/ticket-receipt.dtd
<!ELEMENT CommonElements (text | img | table | linebreak | cut | beep | code | #PCDATA)*>

        <!ELEMENT text (#PCDATA)>
        <!ATTLIST text
                underline (true | false) "false"
                bold (true | false) "false"
                special (none | doubleH | doubleW | quad) "none"
                font (A|B) #IMPLIED
                textHeight CDATA #IMPLIED
                textWidth CDATA #IMPLIED
                >

        <!ELEMENT table (tr)*>
        <!ELEMENT tr (td)*>
        <!ELEMENT td (#PCDATA)>
        <!ATTLIST td
                alignment (LEFT | CENTER | RIGHT) #IMPLIED
                bold (true | false) "false"
                width CDATA #IMPLIED
                cols CDATA #IMPLIED
                >

        <!ELEMENT img EMPTY>
        <!ATTLIST img
                src CDATA #REQUIRED
                >

        <!ELEMENT code EMPTY>
        <!ATTLIST code
                type (QR | Code128) #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT linebreak EMPTY>
        <!ELEMENT line EMPTY>
        <!ATTLIST line
                char CDATA #IMPLIED
                >

        <!ELEMENT cut EMPTY>
        <!ATTLIST cut
                vertical CDATA #IMPLIED
                >
        <!ELEMENT beep EMPTY>

        <!ELEMENT alignment (text | img | table | linebreak | cut | beep | code | invert | alignment)*>
        <!ATTLIST alignment
                alignment (LEFT | CENTER | RIGHT) #REQUIRED
                >

        <!ELEMENT invert (text | img | table | linebreak | cut | beep | code | invert | alignment)*>
        <!ATTLIST invert
                invert (true | false) #REQUIRED
                >

        <!ELEMENT ticket (text | img | table | linebreak | cut | beep | code | invert | alignment)*>
        <!ATTLIST ticket
                width CDATA #REQUIRED
                >

=== cabrasky/thermal-ticket-printer/templates/ticket-template.xml
<!DOCTYPE ticket SYSTEM "ticket-receipt.dtd">
<ticket width="32">
    <alignment alignment="CENTER">
        <img src="templates/resources/logo.png"/>
        <text underline="true" bold="true">Store Name</text>
        <linebreak/>
        <text>123 Main Street, City</text>
        <linebreak/>
        <text>Date: 2024-01-30</text>
    </alignment>
    <linebreak/>

    <table>
        <tr>
            <td width=".4">Item</td>
            <td width=".2">Qty</td>
            <td>Price</td>
        </tr>
        <tr>
            <td width=".4" alignment="LEFT">Item 1</td>
            <td width=".2" alignment="RIGHT">2</td>
            <td alignment="RIGHT">10.99</td>
        </tr>
        <tr>
            <td width=".4" alignment="LEFT">Item 2</td>
            <td width=".2" alignment="RIGHT">1</td>
            <td alignment="RIGHT">5.99</td>
        </tr>
    </table>
    <linebreak/>

    <text bold="true">Total: 16.98â‚¬</text>
    <linebreak/>

    <text>Thank you for shopping with us!</text>
</ticket>

=== cabrasky/thermal-ticket-printer/example/ticket.xml
<!DOCTYPE ticket SYSTEM "node_modules/thermal-ticket-printer/templates/ticket-receipt.dtd">
<ticket width="32">
    <alignment alignment="CENTER">
        <img src="node_modules/thermal-ticket-printer/templates/resources/logo.png"/>
        <text underline="true" bold="true">Store Name</text>
        <linebreak/>
        <text>Date: {{ current_date }}</text>
    </alignment>
    <linebreak/>

    <table>
        <tr>
            <td width=".4" alignment="LEFT">Item</td>
            <td width=".1" alignment="LEFT">Qty</td>
            <td width=".1" alignment="LEFT">Price</td>
        </tr>
        {{#items}}
        <tr>
            <td width=".4" alignment="LEFT">{{ name }}</td>
            <td width=".1" alignment="LEFT">{{ quantity }}</td>
            <td alignment="LEFT">{{ price }}</td>
        </tr>
        {{/items}}
    </table>
    <linebreak/>

    <text bold="true">Total: {{ total_amount }}</text>
    <linebreak/>

    <text>Thank you for shopping with us!</text>
</ticket>
